name: Call Kernel Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    uses: empyrean-eu/bunny-example/.github/workflows/build_conditional.yml@main
    with:
      kernel_version: "6.13"
      defconfig: |
        CONFIG_TMPFS=y
        CONFIG_POSIX_TIMERS=y
        CONFIG_HIGH_RES_TIMERS=y
        CONFIG_NAMESPACES=y
        CONFIG_EXPERT=y
        CONFIG_HYPERVISOR_GUEST=y
        CONFIG_PARAVIRT=y
        CONFIG_PVH=y
        CONFIG_JUMP_LABEL=y
        CONFIG_BINFMT_MISC=y
        CONFIG_NET=y
        CONFIG_UNIX=y
        CONFIG_INET=y
        CONFIG_IP_MULTICAST=y
        CONFIG_IP_PNP=y
        CONFIG_IP_PNP_DHCP=y
        CONFIG_PCI=y
        CONFIG_DEVTMPFS=y
        CONFIG_DEVTMPFS_MOUNT=y
        CONFIG_VIRTIO_BLK=y
        CONFIG_NETDEVICES=y
        CONFIG_VIRTIO_NET=y
        CONFIG_SERIAL_8250=y
        CONFIG_SERIAL_8250_CONSOLE=y
        CONFIG_SERIAL_8250_NR_UARTS=1
        CONFIG_SERIAL_8250_RUNTIME_UARTS=1
        CONFIG_PTP_1588_CLOCK_MOCK=y
        CONFIG_VIRT_DRIVERS=y
        CONFIG_VIRTIO_PCI=y
        CONFIG_VIRTIO_MMIO=y
        CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y
        CONFIG_EXT2_FS=y
        CONFIG_EXT2_FS_XATTR=y
        CONFIG_EXT2_FS_POSIX_ACL=y
        CONFIG_EXT2_FS_SECURITY=y
        CONFIG_CRYPTO=y
        CONFIG_CRYPTO_CRC32C=y
        CONFIG_FRAME_WARN=1024
        CONFIG_DEBUG_MEMORY_INIT=y
        CONFIG_UNWINDER_FRAME_POINTER=y
    secrets: inherit

  #retrieve-kernel:
  #  needs: build-linux
  #  uses: empyrean-eu/bunny-example/.github/workflows/get_artifact.yml@main
  #  #with:
  #    #kernel_version: ${{ inputs.kernel_version }}
